// Customs HS Code Lookup
// HS code lookup, tariff calculation, and customs duty estimation for international trade and cross-border logistics automation.
// Auto-generated by @ph-itdev/logistics-pipeline


const COMMON_HS_CODES = {
  '8471': { desc: 'Computers & accessories', dutyRate: 0, vatRate: 0 },
  '6110': { desc: 'Knitted apparel', dutyRate: 12, vatRate: 18 },
  '8517': { desc: 'Telecom equipment', dutyRate: 0, vatRate: 18 },
  '8703': { desc: 'Motor vehicles', dutyRate: 60, vatRate: 28 },
  '9403': { desc: 'Furniture', dutyRate: 20, vatRate: 18 },
  '3004': { desc: 'Pharmaceuticals', dutyRate: 10, vatRate: 12 },
  '2201': { desc: 'Mineral water', dutyRate: 30, vatRate: 18 },
  '7108': { desc: 'Gold', dutyRate: 15, vatRate: 3 },
  '1006': { desc: 'Rice', dutyRate: 40, vatRate: 5 },
  '8415': { desc: 'Air conditioning', dutyRate: 20, vatRate: 28 },
};

function lookupHSCode(code) {
  const sixDigit = code.substring(0, 4);
  const entry = COMMON_HS_CODES[sixDigit];
  if (!entry) return null;
  return { hsCode: code, description: entry.desc, dutyRate: entry.dutyRate, vatRate: entry.vatRate };
}

function calculateCustomsDuty({ hsCode, cifValue, quantity = 1, originCountry }) {
  const lookup = lookupHSCode(hsCode);
  if (!lookup) return { error: 'HS code not found in database' };
  const basicDuty = +(cifValue * lookup.dutyRate / 100).toFixed(2);
  const vat = +((cifValue + basicDuty) * lookup.vatRate / 100).toFixed(2);
  const totalDuty = +(basicDuty + vat).toFixed(2);
  return { hsCode, description: lookup.description, cifValue, quantity, dutyRate: lookup.dutyRate, vatRate: lookup.vatRate, basicDuty, vat, totalDuty, effectiveRate: +((totalDuty / cifValue) * 100).toFixed(1) };
}

function classifyByDescription(description) {
  const lower = description.toLowerCase();
  const matches = [];
  for (const [code, entry] of Object.entries(COMMON_HS_CODES)) {
    if (entry.desc.toLowerCase().split(' ').some(w => lower.includes(w))) matches.push({ code, ...entry });
  }
  return matches.sort((a, b) => b.dutyRate - a.dutyRate);
}


module.exports = { lookupHSCode, calculateCustomsDuty, classifyByDescription, COMMON_HS_CODES };
